# -*- coding: utf-8 -*-
"""ana1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/rahafhammed/8cdd44581b4bb27ad8ea1b513fffceb3/ana1.ipynb
"""

pip install boto3

import pandas as pd
import boto3
import io
import getpass
aws_access_key = getpass.getpass('Enter AWS Access Key: ')
REGION = 'eu-central-1'

s3_client = boto3.client(
    's3',
    aws_access_key_id=ACCESS_KEY,
    aws_secret_access_key=SECRET_KEY,
    region_name=REGION
)

bucket_name = 'amazon3-erstedate'
file_key = 'raw/Online Retail.xlsx'

obj = s3_client.get_object(Bucket=bucket_name, Key=file_key)

data = obj['Body'].read()
df = pd.read_excel(io.BytesIO(data))


print("✅ ")
df.head()

# Berechnung der fehlenden Werte vor der Bereinigung
# Dies hilft uns zu verstehen, wie viele Datenlücken existieren
missing_values_count = df.isnull().sum()
print("Anzahl der fehlenden Werte pro Spalte vor der Bereinigung:")
print(missing_values_count)

# 1. Zeilen mit fehlenden Werten in wichtigen Spalten entfernen
# Ein Datensatz ohne CustomerID oder Description ist für die Analyse unbrauchbar.
df_cleaned = df.dropna(subset=['CustomerID', 'Description'])

# 2. Ausreißer und fehlerhafte Daten filtern
# Sicherstellen, dass die Menge (Quantity) und der Einzelpreis (UnitPrice) größer als Null sind.
# Rücksendungen oder Stornierungen (negative Werte) werden hier ausgeschlossen.
df_cleaned = df_cleaned[(df_cleaned['Quantity'] > 0) & (df_cleaned['UnitPrice'] > 0)]

# 3. Standardisierung des Datumsformats
# Konvertiert die Spalte 'InvoiceDate' in ein einheitliches Datetime-Objekt für Zeitreihenanalysen.
df_cleaned['InvoiceDate'] = pd.to_datetime(df_cleaned['InvoiceDate'])

# Ausgabe der Ergebnisse zur Kontrolle
print(f"\nAnzahl der Zeilen vor der Bereinigung: {len(df)}")
print(f"Anzahl der Zeilen nach der Bereinigung: {len(df_cleaned)}")
print(f"Gesamtanzahl der entfernten Zeilen: {len(df) - len(df_cleaned)}")

print(df.isnull().mean() * 100) # Zeigt den Prozentsatz der fehlenden Werte

import io

# FEHLERBEHEBUNG: Typkonvertierung für StockCode
# Das Problem: StockCode enthält eine Mischung aus Zahlen (int) und Text (str).
# Wir zwingen alle Werte in das String-Format, um den ArrowTypeError zu vermeiden.

# 1. Spalten explizit als String formatieren
if 'StockCode' in df_cleaned.columns:
    df_cleaned['StockCode'] = df_cleaned['StockCode'].astype(str)

if 'CustomerID' in df_cleaned.columns:
    # Zuerst in float/int umwandeln, um .0 zu entfernen, dann in string
    df_cleaned['CustomerID'] = df_cleaned['CustomerID'].astype(float).astype(int).astype(str)

# 2. DataFrame in das Parquet-Format konvertieren
parquet_buffer = io.BytesIO()

try:
    # Wir nutzen engine='pyarrow', um die Schema-Konventionen einzuhalten
    df_cleaned.to_parquet(parquet_buffer, index=False, engine='pyarrow')

    # 3. Upload der verarbeiteten Datei in den S3-Bucket
    output_key = 'processed/online_retail_cleaned.parquet'

    s3_client.put_object(
        Bucket=bucket_name,
        Key=output_key,
        Body=parquet_buffer.getvalue()
    )
    print(f"✅ Erfolg! Die Spalte 'StockCode' wurde bereinigt und die Datei unter s3://{bucket_name}/{output_key} gespeichert.")

except Exception as e:
    print(f"❌ Erneuter Fehler beim Speichern: {e}")

import io

# 1. Vorbereitung des Byte-Streams für Excel
# Wir erstellen einen Puffer im Arbeitsspeicher für die Excel-Datei.
excel_buffer = io.BytesIO()

# 2. DataFrame in das Excel-Format konvertieren
# Wir nutzen 'openpyxl' als Engine. 'index=False' verhindert das Speichern der Zeilennummern.
with pd.ExcelWriter(excel_buffer, engine='openpyxl') as writer:
    df_cleaned.to_excel(writer, index=False, sheet_name='Bereinigte_Daten')

# 3. Upload der Excel-Datei in den S3-Bucket (Processed Folder)
output_key_excel = 'processed/online_retail_cleaned.xlsx'

try:
    s3_client.put_object(
        Bucket=bucket_name,
        Key=output_key_excel,
        Body=excel_buffer.getvalue()
    )
    print(f"✅ Excel-Datei wurde erfolgreich unter s3://{bucket_name}/{output_key_excel} gespeichert.")
except Exception as e:
    print(f"❌ Fehler beim Hochladen der Excel-Datei: {e}")

!pip install matplotlib seaborn

import matplotlib.pyplot as plt
import seaborn as sns

# Einstellung des Designs (Deutsches Zeitformat und professionelles Layout)
sns.set(style="whitegrid")
plt.figure(figsize=(12, 6))

# 1. Umsatz nach Ländern (Top 10)
# Wir berechnen zuerst den Gesamtumsatz (TotalAmount)
df_cleaned['TotalAmount'] = df_cleaned['Quantity'] * df_cleaned['UnitPrice']

top_countries = df_cleaned.groupby('Country')['TotalAmount'].sum().sort_values(ascending=False).head(10)

# Visualisierung mit Seaborn
sns.barplot(x=top_countries.values, y=top_countries.index, palette='viridis')
plt.title('Top 10 Länder nach Gesamtumsatz', fontsize=15)
plt.xlabel('Umsatz (Revenue)', fontsize=12)
plt.ylabel('Land', fontsize=12)
plt.show()

# 2. Die 10 meistverkauften Produkte (Best Sellers)
top_products = df_cleaned.groupby('Description')['Quantity'].sum().sort_values(ascending=False).head(10)

plt.figure(figsize=(12, 6))
sns.barplot(x=top_products.values, y=top_products.index, palette='magma')
plt.title('Top 10 meistverkaufte Produkte (Menge)', fontsize=15)
plt.xlabel('Verkaufte Menge', fontsize=12)
plt.ylabel('Produktbeschreibung', fontsize=12)
plt.show()

# 3. Monatliche Umsatzentwicklung (Trend-Analyse)
# Wir setzen das Datum als Index für die Zeitreihenanalyse
df_cleaned.set_index('InvoiceDate', inplace=True)
monthly_sales = df_cleaned['TotalAmount'].resample('M').sum()

plt.figure(figsize=(12, 6))
plt.plot(monthly_sales, marker='o', linestyle='-', color='b')
plt.title('Monatliche Umsatzentwicklung (Zeitreihe)', fontsize=15)
plt.xlabel('Datum', fontsize=12)
plt.ylabel('Gesamtumsatz', fontsize=12)
plt.grid(True)
plt.show()

# Index wieder zurücksetzen für weitere Analysen
df_cleaned.reset_index(inplace=True)

# --- RFM Analysis (Customer Segmentation) ---
# 1. Recency: Wie viele Tage seit dem letzten Kauf?
# 2. Frequency: Wie oft hat der Kunde gekauft?
# 3. Monetary: Wie viel Geld hat der Kunde ausgegeben?

import datetime as dt

# Wir setzen den Referenzpunkt auf einen Tag nach dem letzten Datum im Datensatz
snapshot_date = df_cleaned['InvoiceDate'].max() + dt.timedelta(days=1)

rfm = df_cleaned.groupby('CustomerID').agg({
    'InvoiceDate': lambda x: (snapshot_date - x.max()).days,
    'InvoiceNo': 'count',
    'TotalAmount': 'sum'
})

# Spalten umbenennen
rfm.rename(columns={
    'InvoiceDate': 'Recency',
    'InvoiceNo': 'Frequency',
    'TotalAmount': 'MonetaryValue'
}, inplace=True)

# 4. Scoring (Einteilung in 4 Stufen)
rfm['R_Score'] = pd.qcut(rfm['Recency'], 4, labels=[4, 3, 2, 1])
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 4, labels=[1, 2, 3, 4])
rfm['M_Score'] = pd.qcut(rfm['MonetaryValue'], 4, labels=[1, 2, 3, 4])

# Berechnung des RFM-Gesamtwerts
rfm['RFM_Score'] = rfm[['R_Score', 'F_Score', 'M_Score']].sum(axis=1)

print("Die ersten 5 Kundensegmente (RFM):")
print(rfm.head())